# Generated by Django 3.2.7 on 2023-01-31 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='Date | Дата')),
                ('Shoulders', models.IntegerField(verbose_name='Shoulders, sm. | Плечи, см.')),
                ('Chest', models.IntegerField(verbose_name='Chest, sm. | Грудь, см.')),
                ('Waist', models.IntegerField(verbose_name='Waist, sm. | Талия, см.')),
                ('Buttocks', models.IntegerField(verbose_name='Buttocks, sm. | Ягодицы, см.')),
                ('Hips', models.IntegerField(verbose_name='Hips, sm. | Бёдра, см.')),
                ('Weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Weight, kg. | Вес, кг.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User | Пользователь')),
            ],
            options={
                'verbose_name': 'Body measurements',
                'verbose_name_plural': 'Body measurements',
                'ordering': ['-Date'],
            },
        ),
    ]
